### ISSUE TITLE
btrbk fails if "volume" is "/"

### ISSUE THREAD

**Issue by digint** [digint/btrbk#15]
The following use-case was not considered (thanks Bernd):
```
volume /
  subvolume @home
    target send-receive    /mnt/btrfs_backup
```
This will be fixed in refactored btrbk, to be released soon.

**Comment by bk1285** [comment]
Hi,

rerunning with your quick fix leads to 

    btrbk command line client, version 0.16  (Tue Apr 28 22:38:40 2015)
    WARNING: Skipping subvolume section: Subvolume "@home" not present in btrfs subvolume list for "/"
    Completed within: 0s  (Tue Apr 28 22:38:40 2015)
    --------------------------------------------------------------------------------
    Backup Summary (btrbk command line client, version 0.16)

    Date:   Tue Apr 28 22:38:40 2015
    Config: /foo/bar/btrbk.conf

    Legend:
    +++  created subvolume (source snapshot)
    ---  deleted subvolume (source snapshot)
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
    --------------------------------------------------------------------------------
    //@home
    !!! Subvolume "@home" aborted: Subvolume "@home" not present in btrfs subvolume list for "/"

    NOTE: Some errors occurred, which may result in missing backups!
    Please check warning and error messages above.

    NOTE: Dryrun was active, none of the operations above were actually executed!

I suspect this line to fail:

    die("subvolume info not present: $sroot/$svol") unless($svol_node);

... but sorry: I have no clue how to fix this in perl ...

**Comment by digint** [comment]
I just merged the fresh and clean refactored code to master. A quick test shows me that your use-case works with this. Can you please try this one out and tell me the results?

**Comment by digint** [comment]
Fix included in btrbk-0.17.0

**Comment by bk1285** [comment]
Hi,

finally I gave the new version a try. ...but unfortuneatly, it's still failing... ? :/

Regards,
Bernd

btrbk command line client, version 0.17.0  (Thu May  7 23:30:14 2015)
Using configuration: /home/hamster/.vim/pc_config_bkps/hamster-ProLiant-MicroServer_a7a5fed1/btrbk.conf
WARNING: Skipping subvolume "//@home": Failed to fetch subvolume detail
Completed within: 0s  (Thu May  7 23:30:14 2015)
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.17.0)

    Date:   Thu May  7 23:30:14 2015
    Config: /foo/bar/btrbk.conf

Legend:
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
//@home
!!! Subvolume "//@home" aborted: Failed to fetch subvolume detail

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.

NOTE: Dryrun was active, none of the operations above were actually executed!

**Comment by bk1285** [comment]
... wouldn't it be feasible to set volume to "", if it's set to "/" within the config file?
The subvolume would then be assembled as "" + "/" + "@home" instead of "/" + "/" + "@home".

**Comment by digint** [comment]
Strange, I just repeated my test case for this, and it works for me:

/tmp/btrbk.conf:
```
snapshot_create_always yes
volume /
  subvolume @home
```

testcase:
```
# cat /tmp/btrfs.conf
snapshot_create_always yes
volume /
  subvolume @home

# btrfs sub create /\@home
# btrbk -c /tmp/btrbk.conf dryrun
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.17.0)

    Date:   Fri May  8 12:42:30 2015
    Config: /tmp/btrbk.conf

Legend:
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
//@home
+++ ///@home.20150508
```

The only possible difference might be that you have "/" mounted as `subvolid=0`? (Here it's mounted with: `subvol=rootfs`) Is that the case?

What is your output of `btrfs sub show /\@home`?

To further investigate this, I will also need your `btrbk.conf` and a full trace log: `btrbk -l trace -c /foo/bar/btrbk.conf`.

Regarding your second question: No, I can't really change the volume/subvolume declarations. For this single use case, it will assemble the path as `//@home`, but this is not an issue. Unix does not care about multiple slashes in paths (try `ls /////foo///bar`).

**Comment by bk1285** [comment]
Hi,

sorry, my fault: Since you closed this issue, my server stopped booting...
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1445252
:-/

After recovering it manually, I now realized, that the subvolume @home is somehow not listed yet, causing your script to fail... :o 

Regards,
Bernd

**Comment by digint** [comment]
Closing the bug, as it was a problem on the user side.
@bk1285 please reopen if it is still not working after you fixed your problems.

**Comment by bk1285** [comment]
Hi,
just another point...: Is it also possible to backup '/' as subvolume (to store my PCs configuration)?

Using

    volume /
      subvolume /

will result in a parsing error of the config file...

Regards,
Bernd

**Comment by digint** [comment]
Hi

I added an (unfinished) FAQ to the "faq" branch:

https://github.com/digint/btrbk/blob/faq/doc/FAQ.md

I hope this covers your question. Comments are welcome!
